In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from imblearn.over_sampling import SMOTE, RandomOverSampler
from imblearn.under_sampling import RandomUnderSampler

In [8]:
df = pd.read_csv('training_set.csv')
df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,sep_status,aug_status,jul_status,jun_status,may_status,...,jun_bill,may_bill,apr_bill,sep_payment,aug_payment,jul_payment,jun_payment,may_payment,apr_payment,default.payment.next.month
0,0.040404,0.0,0.333333,0.0,0.344828,0.2,0.2,0.2,0.2,0.2,...,0.171654,0.091738,0.268766,0.001466,0.000721,0.001289,0.000604,0.000853,0.000670,0.0
1,0.090909,0.0,0.666667,0.0,0.258621,0.4,0.2,0.2,0.4,0.2,...,0.265655,0.192602,0.353274,0.005976,0.009861,0.000000,0.006816,0.021569,0.039723,1.0
2,0.121212,1.0,0.333333,0.5,0.068966,0.2,0.2,0.2,0.2,0.2,...,0.165034,0.085802,0.264973,0.002290,0.000594,0.002455,0.000000,0.000000,0.000000,0.0
3,0.151515,0.0,0.333333,0.5,0.120690,0.1,0.1,0.1,0.2,0.2,...,0.163882,0.084337,0.265334,0.002358,0.001285,0.002232,0.002415,0.004689,0.003286,0.0
4,0.121212,0.0,0.000000,0.5,0.068966,0.1,0.1,0.1,0.1,0.1,...,0.161160,0.081587,0.261359,0.001741,0.003589,0.001807,0.001525,0.001161,0.000000,0.0

In [11]:
X, y = df.iloc[:,:-1], df.iloc[:, -1]

In [14]:
#SMOTE
sm = SMOTE(random_state=0)
X_smote, y_smote = sm.fit_resample(X,y)

X_smote['default.payment.next.month'] = y_smote

In [15]:
#RandomOverSample
ros = RandomOverSampler(random_state=0)
X_ros, y_ros = ros.fit_resample(X,y)

X_ros['default.payment.next.month'] = y_ros

In [27]:
#RandomOverSample
rus = RandomUnderSampler(random_state=0)
X_rus, y_rus = rus.fit_resample(X,y)

X_rus['default.payment.next.month'] = y_rus

In [28]:
print(df['default.payment.next.month'].value_counts())
print(X_smote['default.payment.next.month'].value_counts())
print(X_ros['default.payment.next.month'].value_counts())
print(X_rus['default.payment.next.month'].value_counts())

0.0    16355
1.0     4645
Name: default.payment.next.month, dtype: int64
0.0    16355
1.0    16355
Name: default.payment.next.month, dtype: int64
0.0    16355
1.0    16355
Name: default.payment.next.month, dtype: int64
0.0    4645
1.0    4645
Name: default.payment.next.month, dtype: int64

In [29]:
X_ros.to_csv('training_ROS.csv', index=False)
X_rus.to_csv('training_RUS.csv', index=False)
X_smote.to_csv('training_SMOTE.csv', index=False)